# Generated by Django 4.2.5 on 2023-10-01 07:29

import DigitalLurker.utils
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField(max_length=64)),
                ('description', models.TextField(max_length=256, null=True)),
                ('main_image', models.ImageField(default='defaults/places/default.png', upload_to=DigitalLurker.utils.uuid_upload_to)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to=DigitalLurker.utils.uuid_upload_to)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PlacePhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
